
- name: Launch EC2 instance
  amazon.aws.ec2_instance:
    name: "Ansible-EC2"
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_ami }}"
    region: "{{ aws_region }}"
    wait: yes
    count: 1
