---
# tasks file for Azure
- name: Create resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"

- name: Create virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    name: "{{ vm_name }}-vnet"
    resource_group: "{{ resource_group }}"
    address_prefixes: "10.0.0.0/16"

- name: Create subnet
  azure.azcollection.azure_rm_subnet:
    name: "{{ vm_name }}-subnet"
    resource_group: "{{ resource_group }}"
    virtual_network: "{{ vm_name }}-vnet"
    address_prefix: "10.0.1.0/24"

- name: Create public IP
  azure.azcollection.azure_rm_publicipaddress:
    name: "{{ vm_name }}-pip"
    resource_group: "{{ resource_group }}"
    allocation_method: Static

- name: Create NIC
  azure.azcollection.azure_rm_networkinterface:
    name: "{{ vm_name }}-nic"
    resource_group: "{{ resource_group }}"
    virtual_network: "{{ vm_name }}-vnet"
    subnet: "{{ vm_name }}-subnet"
    public_ip_name: "{{ vm_name }}-pip"

- name: Create VM
  azure.azcollection.azure_rm_virtualmachine:
    name: "{{ vm_name }}"
    resource_group: "{{ resource_group }}"
    vm_size: "{{ vm_size }}"
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    network_interfaces: "{{ vm_name }}-nic"
    image: "{{ image }}"
